import type { Spot, Festival, Bundle, Theme, ThemeInfo, Season } from '@/shared/types';

export const THEMES: Record<Theme, ThemeInfo> = {
  forest:    { label: '숲',      color: '#3A6B47', bg: '#E4EEE8', icon: '🌲' },
  wetland:   { label: '습지',    color: '#3A6B7C', bg: '#E0ECF0', icon: '🌿' },
  ocean:     { label: '바다',    color: '#2B5F9E', bg: '#E0EAF5', icon: '🐚' },
  farm:      { label: '농촌',    color: '#7A5A14', bg: '#F2EAD6', icon: '🌾' },
  wildlife:  { label: '야생동물', color: '#6B4226', bg: '#EDE0D8', icon: '🦋' },
  astronomy: { label: '천문',    color: '#3A3A7A', bg: '#E0E0F0', icon: '⭐' },
  geology:   { label: '지질',    color: '#5B4B2E', bg: '#EAE4D8', icon: '🪨' },
};

export const REGIONS = ['서울','경기','인천','강원','충북','충남','대전','전북','전남','광주','경북','경남','대구','부산','울산','제주'];

export const SEASONS: Record<Season, string> = {
  spring: '봄', summer: '여름', fall: '가을', winter: '겨울', 'year-round': '연중'
};

export const SPOTS: Spot[] = [
  {
    id:1, name:'순천만 국가정원', region:'전남', theme:'wetland',
    img:'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80',
    description:'세계 최대 규모의 갈대밭과 철새 도래지. 탐조 프로그램으로 아이들이 자연 생태계를 직접 관찰할 수 있어요.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['탐조 체험','갈대밭 산책','자연 관찰 교실'],
    season:['spring','fall','winter'], rating:4.8, reviews:1243, rank:1,
    hours:'매일 09:00–18:00', admission:'성인 8,000원 / 어린이 5,000원',
    restaurant:'정원 내 어린이 메뉴 레스토랑 운영 중',
    safety:'탐방로 전구간 유아차 접근 가능. 겨울 낙엽 시 미끄럼 주의.',
    isNew:false, distance:3.2,
  },
  {
    id:2, name:'제주 곶자왈 생태숲', region:'제주', theme:'forest',
    img:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
    description:'화산암반 위에 형성된 독특한 열대·온대 식물의 공존 지대. 용암길을 직접 걸으며 탐험할 수 있어요.',
    stroller:false, nursing:true, parking:true, accessible:false, hasPrograms:true,
    programs:['숲 해설 투어','곤충 관찰','야생화 채집'],
    season:['spring','summer','fall'], rating:4.7, reviews:892, rank:2,
    hours:'매일 09:00–17:00', admission:'무료',
    restaurant:'인근 제주 향토 식당 (아이 메뉴 O)',
    safety:'용암 지형으로 울퉁불퉁. 걸음마기 이상 권장. 튼튼한 신발 필수.',
    isNew:false, distance:12.1,
  },
  {
    id:3, name:'서울 강서습지생태공원', region:'서울', theme:'wetland',
    img:'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600&q=80',
    description:'한강 하류의 자연 습지 생태계. 도심에서 가장 가깝게 자연을 만날 수 있는 곳으로, 모든 연령 접근 가능.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['생태 해설 투어','탐조 교실'],
    season:['spring','summer','fall'], rating:4.5, reviews:2104, rank:3,
    hours:'상시 개방', admission:'무료',
    restaurant:'공원 내 카페 (어린이 메뉴)',
    safety:'전구간 포장 산책로. 유아차 편리. 물가 접근 시 보호자 동행 필수.',
    isNew:false, distance:0.8,
  },
  {
    id:4, name:'국립생태원', region:'충남', theme:'wildlife',
    img:'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&q=80',
    description:'세계 5대 기후대 생태계를 한 곳에서. 에코리움 실내관으로 날씨 상관없이 체험 가능해 아이들에게 최고 인기.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['에코리움 탐방','곤충 체험관','맹꽁이 논'],
    season:['year-round'], rating:4.9, reviews:3201, rank:4,
    hours:'화–일 09:30–18:00 (월 휴관)', admission:'성인 5,000원 / 어린이 3,000원',
    restaurant:'에코센터 레스토랑 (어린이 세트 O)',
    safety:'실내 관람 가능. 우천 시에도 쾌적한 관람 가능.',
    isNew:false, distance:8.5,
  },
  {
    id:5, name:'대관령 양떼목장', region:'강원', theme:'farm',
    img:'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&q=80',
    description:'구름 위의 초원에서 양 먹이주기 체험. 드넓은 목초지가 아이들의 뛰어놀기 공간이 되어줘요.',
    stroller:false, nursing:false, parking:true, accessible:false, hasPrograms:true,
    programs:['양 먹이주기','목장 트레킹'],
    season:['spring','summer','fall'], rating:4.6, reviews:1876, rank:5,
    hours:'매일 09:00–17:30', admission:'성인 4,000원 / 어린이 3,000원',
    restaurant:'목장 내 카페 (음료·간식)',
    safety:'경사진 지형. 유아차 비권장. 튼튼한 신발 필수.',
    isNew:false, distance:15.3,
  },
  {
    id:6, name:'울진 금강소나무숲길', region:'경북', theme:'forest',
    img:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
    description:'수령 500년 이상의 금강소나무 군락. 산림청 숲 해설가와 함께하는 가이드 투어로 예약 필수.',
    stroller:false, nursing:false, parking:true, accessible:false, hasPrograms:true,
    programs:['숲 해설 투어 (예약 필수)'],
    season:['spring','summer','fall'], rating:4.7, reviews:654, rank:6,
    hours:'화–일 09:00–15:00', admission:'무료 (해설 투어 예약 필수)',
    restaurant:'인근 울진 대게 음식점',
    safety:'산림 보호를 위해 지정 탐방로 이탈 금지. 5세 이상 권장.',
    isNew:true, distance:42.1,
  },
  {
    id:7, name:'진도 신비의 바닷길', region:'전남', theme:'ocean',
    img:'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80',
    description:'1년에 몇 번 조수간만의 차로 바닷길이 열리는 신비로운 현상. 아이들이 바다 바닥을 직접 걸을 수 있어요.',
    stroller:false, nursing:false, parking:true, accessible:false, hasPrograms:false,
    programs:[],
    season:['spring','fall'], rating:4.4, reviews:987, rank:7,
    hours:'조수 시간표 확인 필요', admission:'무료',
    restaurant:'진도 특산 해산물 식당가',
    safety:'조개껍질로 발 부상 위험. 물장화 권장. 조수 시간 엄수.',
    isNew:false, distance:28.7,
  },
  {
    id:8, name:'철원 두루미 탐조지', region:'강원', theme:'wildlife',
    img:'https://images.unsplash.com/photo-1490718720478-364a07a997cd?w=600&q=80',
    description:'천연기념물 두루미 가족을 가장 가까이서 볼 수 있는 탐조 명소. 망원경 체험 제공.',
    stroller:true, nursing:false, parking:true, accessible:true, hasPrograms:true,
    programs:['탐조 프로그램','생태 사진 교실'],
    season:['winter'], rating:4.6, reviews:432, rank:8,
    hours:'12–2월 매일 08:00–17:00', admission:'무료',
    restaurant:'인근 식당 한정 운영',
    safety:'겨울철 방문. 방한 용품 필수. 영하 날씨 대비 요망.',
    isNew:false, distance:35.4,
  },
  {
    id:9, name:'고흥 우주천문과학관', region:'전남', theme:'astronomy',
    img:'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&q=80',
    description:'나로우주센터 인근 우주 테마 과학관. 로켓 발사 장면을 볼 수 있는 유일한 공간.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['천체 관측','우주 VR 체험','로켓 발사 관람'],
    season:['year-round'], rating:4.5, reviews:765, rank:9,
    hours:'화–일 10:00–18:00', admission:'성인 3,000원 / 어린이 2,000원',
    restaurant:'과학관 구내식당',
    safety:'실내 관람 중심. 모든 연령 가능.',
    isNew:true, distance:55.2,
  },
  {
    id:10, name:'화순 고인돌 유적지', region:'전남', theme:'geology',
    img:'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=600&q=80',
    description:'유네스코 세계문화유산 고인돌 군락. 선사시대 이야기로 아이들의 역사 상상력을 자극해요.',
    stroller:true, nursing:false, parking:true, accessible:true, hasPrograms:true,
    programs:['역사 해설 투어','선사 체험 교실'],
    season:['spring','summer','fall'], rating:4.3, reviews:543, rank:10,
    hours:'매일 09:00–18:00', admission:'무료',
    restaurant:'인근 한정식 식당',
    safety:'잔디밭 구간 유아차 주의. 해설사 동행 권장.',
    isNew:false, distance:22.8,
  },
];

export const FESTIVALS: Festival[] = [
  {
    id:101, name:'양평 들꽃 축제', region:'경기', theme:'farm',
    img:'https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?w=600&q=80',
    description:'5월 봄을 가득 채우는 야생화와 들꽃 축제. 꽃 묘종 가져가기, 압화 만들기 등 아이들 프로그램 풍성.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['압화 만들기','꽃다발 체험','버섯 관찰'],
    dateRange:'2025.05.01–05.31', rating:4.7, reviews:1432, rank:1,
    season:['spring'], isNew:false, distance:6.3, admission:'무료',
  },
  {
    id:102, name:'창녕 우포늪 생태 축제', region:'경남', theme:'wetland',
    img:'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80',
    description:'국내 최대 내륙 습지 우포늪의 봄을 맞이하는 축제. 가시연꽃 관찰, 민물고기 잡기 체험.',
    stroller:true, nursing:false, parking:true, accessible:false, hasPrograms:true,
    programs:['가시연꽃 관찰','민물고기 잡기','갈대 공예'],
    dateRange:'2025.04.15–04.20', rating:4.5, reviews:876, rank:2,
    season:['spring'], isNew:false, distance:18.4, admission:'무료',
  },
  {
    id:103, name:'제주 유채꽃 축제', region:'제주', theme:'farm',
    img:'https://images.unsplash.com/photo-1522748906645-95d8adfd52c7?w=600&q=80',
    description:'제주도를 노랗게 물들이는 유채꽃 물결. 산방산을 배경으로 봄 나들이의 정수.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:false,
    programs:[], dateRange:'2025.03.20–04.10', rating:4.8, reviews:3210, rank:3,
    season:['spring'], isNew:false, distance:45.0, admission:'무료',
  },
  {
    id:104, name:'홍천 자연 생태 어린이 축제', region:'강원', theme:'forest',
    img:'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=600&q=80',
    description:'어린이를 위해 설계된 생태 체험 축제. 텃밭 농사 체험, 동물 먹이주기, 숲속 어드벤처.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['텃밭 농사 체험','동물 먹이주기','숲속 어드벤처'],
    dateRange:'2025.05.10–05.11', rating:4.9, reviews:654, rank:4,
    season:['spring'], isNew:true, distance:24.1, admission:'어린이 5,000원 / 성인 무료',
  },
  {
    id:105, name:'고창 청보리밭 축제', region:'전북', theme:'farm',
    img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80',
    description:'4–5월 청보리가 물결치는 학원농장의 축제. 바람에 흔들리는 보리밭을 거니는 경험.',
    stroller:true, nursing:false, parking:true, accessible:false, hasPrograms:false,
    programs:[], dateRange:'2025.04.05–05.10', rating:4.6, reviews:1231, rank:5,
    season:['spring'], isNew:false, distance:32.6, admission:'성인 3,000원 / 어린이 1,500원',
  },
  {
    id:106, name:'함평 나비 축제', region:'전남', theme:'wildlife',
    img:'https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?w=600&q=80',
    description:'살아있는 나비와 함께하는 국내 유일의 나비 생태 축제. 나비 표본 만들기, 누에고치 관찰.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['나비 표본 만들기','누에고치 관찰','곤충 사진 교실'],
    dateRange:'2025.05.02–05.12', rating:4.7, reviews:987, rank:6,
    season:['spring'], isNew:false, distance:15.8, admission:'무료',
  },
  {
    id:107, name:'영덕 해양 생태 수산 축제', region:'경북', theme:'ocean',
    img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    description:'동해 바닷가에서 즐기는 수산 생태 체험. 해양 생물 관찰, 조개잡이, 갯벌 체험.',
    stroller:false, nursing:false, parking:true, accessible:false, hasPrograms:true,
    programs:['조개잡이','갯벌 체험','해양 생물 관찰'],
    dateRange:'2025.05.15–05.18', rating:4.4, reviews:543, rank:7,
    season:['spring'], isNew:false, distance:48.2, admission:'무료',
  },
  {
    id:108, name:'별빛 가족 캠프 (화천)', region:'강원', theme:'astronomy',
    img:'https://images.unsplash.com/photo-1464852045489-bccb7d17fe39?w=600&q=80',
    description:'광공해 없는 화천에서 즐기는 별자리 관측 가족 캠프. 천문대 해설사와 함께하는 별 이야기.',
    stroller:false, nursing:false, parking:true, accessible:false, hasPrograms:true,
    programs:['별자리 관측','천체망원경 체험','별빛 사진 촬영'],
    dateRange:'2025.05.23–05.25', rating:4.8, reviews:321, rank:8,
    season:['summer','fall'], isNew:true, distance:38.9, admission:'가족권 50,000원',
  },
  {
    id:109, name:'담양 대나무 생태 축제', region:'전남', theme:'forest',
    img:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description:'대나무 숲 사이를 거니는 시원한 여름 축제. 대나무 공예, 죽마 타기 등 전통 체험.',
    stroller:true, nursing:true, parking:true, accessible:true, hasPrograms:true,
    programs:['대나무 공예','죽마 타기','대숲 산책'],
    dateRange:'2025.05.30–06.01', rating:4.5, reviews:765, rank:9,
    season:['summer'], isNew:false, distance:11.3, admission:'성인 2,000원 / 어린이 무료',
  },
  {
    id:110, name:'서천 갯벌 생태 축제', region:'충남', theme:'ocean',
    img:'https://images.unsplash.com/photo-1494791368093-85217fbbf8de?w=600&q=80',
    description:'유네스코 세계자연유산 갯벌에서 직접 체험. 갯벌 생물 관찰과 조개 캐기로 아이들에게 인기.',
    stroller:false, nursing:true, parking:true, accessible:false, hasPrograms:true,
    programs:['갯벌 생물 관찰','조개 캐기','갯벌 그림 그리기'],
    dateRange:'2025.06.07–06.08', rating:4.6, reviews:876, rank:10,
    season:['summer'], isNew:true, distance:19.7, admission:'무료',
  },
];

export const BUNDLES: Bundle[] = [
  {
    id:201, title:'봄 생태 코스 🌸',
    theme:'wetland',
    distance:'22km', duration:'당일치기',
    stroller:true, region:'서울·경기',
    description:'도심 습지 탐방 후 봄꽃 축제까지. 유아차로 모두 이동 가능한 완벽한 봄 나들이.',
    course: [
      { type:'spot',    item: SPOTS[2],    order:1, tip:'오전 일찍 방문하면 철새를 더 많이 볼 수 있어요. 탐방로 입구에 유아차 대여소가 있어요.' },
      { type:'meal',    label:'점심 식사', icon:'🍱', desc:'공원 내 어린이 메뉴 레스토랑에서 식사. 키즈 메뉴 추천: 유기농 쌈밥 세트.', order:2 },
      { type:'festival',item: FESTIVALS[0], order:3, tip:'오후 1–4시 사이가 가장 붐비지 않아요. 압화 체험은 현장 접수.' },
    ],
  },
  {
    id:202, title:'제주 자연 탐험 🌺',
    theme:'forest',
    distance:'15km', duration:'1박 2일',
    stroller:false, region:'제주',
    description:'유채꽃 물결에서 시작해 신비로운 곶자왈 탐험으로. 제주 자연의 두 얼굴을 만끽하는 패키지.',
    course: [
      { type:'festival',item: FESTIVALS[2], order:1, tip:'산방산 뷰 포인트에서 사진 먼저 찍어두세요. 오전이 빛이 예뻐요.' },
      { type:'meal',    label:'점심 식사', icon:'🍱', desc:'인근 제주 흑돼지 전문점. 어린이 수육 세트 주문 가능.', order:2 },
      { type:'spot',    item: SPOTS[1],    order:3, tip:'곶자왈은 오후 햇빛이 숲으로 들어와 가장 아름다운 시간대예요.' },
      { type:'stay',    label:'숙박', icon:'🏕️', desc:'인근 에코 글램핑장. 자연 친화 숙소로 아이들에게 인기.', order:4 },
      { type:'spot',    item: SPOTS[1],    order:5, label:'2일차: 자유 탐방', tip:'전날 가이드 투어와 다른 구역을 자유롭게 탐방해보세요.' },
    ],
  },
  {
    id:203, title:'전남 생태 완전 정복 🌿',
    theme:'wildlife',
    distance:'45km', duration:'1박 2일',
    stroller:true, region:'전남',
    description:'순천만부터 고인돌까지. 자연·역사·생태를 한 번에 경험하는 알찬 전남 패키지.',
    course: [
      { type:'spot',    item: SPOTS[0],    order:1, tip:'갈대밭이 장관인 오후 4–5시 방문을 추천해요. 해질녘 탐조 프로그램 신청 필수.' },
      { type:'festival',item: FESTIVALS[5], order:2, tip:'나비 방사 행사는 오전 10시 딱 한 번만 진행돼요. 서두르세요!' },
      { type:'meal',    label:'저녁 식사', icon:'🍽️', desc:'순천 특산 짱뚱어탕. 어린이용 된장찌개 세트도 있어요.', order:3 },
      { type:'stay',    label:'숙박', icon:'🏨', desc:'순천만 뷰 펜션. 객실에서 갈대밭 일출 감상 가능.', order:4 },
      { type:'spot',    item: SPOTS[9],    order:5, tip:'2일차 오전에 방문하면 해설사 프로그램 여유있게 참여할 수 있어요.' },
    ],
  },
];

export const DEFAULT_CHECKLISTS: Record<string, string[]> = {
  wetland:   ['유아차','모기 기피제','긴소매 옷','물','간식','여벌 옷','우비'],
  forest:    ['편한 운동화','물','간식','벌레 기피제','긴바지','모자','선크림'],
  ocean:     ['물장화','선크림','모자','여벌 옷','수건','물','간식','방수 주머니'],
  farm:      ['편한 신발','모자','선크림','물','간식','여벌 옷','손 세정제'],
  wildlife:  ['쌍안경','카메라','조용한 옷차림','물','간식','방한 용품(겨울)'],
  astronomy: ['방한 용품','담요','손전등','물','간식','카메라'],
  geology:   ['튼튼한 신발','물','간식','모자','선크림'],
};
